# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-ast
  - id: trailing-whitespace
  - id: check-toml
  - id: end-of-file-fixer

- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.1.0
  hooks:
  - id: add-trailing-comma

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
    - --preserve-quotes
    - --indent=2

- repo: local
  hooks:
  - id: autoflake
    name: autoflake
    entry: poetry run autoflake
    language: system
    types: [python]
    args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]

  - id: black
    name: Format with Black
    entry: poetry run black
    language: system
    types: [python]

  - id: isort
    name: isort
    entry: poetry run isort
    language: system
    types: [python]

  - id: flake8
    name: Check with Flake8
    entry: poetry run flake8
    language: system
    pass_filenames: false
    types: [python]
    args: [--count, .]
